### ISSUE TITLE
Code-related issues

### ISSUE THREAD

**Issue by gmh770980663** [bhargavaurala/accessmath-icfhr2018#1]
I think your project is great and very interesting. However, the download link（AccessMath Dataset
 ，Handwritten Content Detector model and structure file，SSD model ，Handwritten Content Detector from here） requires the account and password of University at Buffalo. Can I give an account password? Or can you put these parts on GitHub?

**Comment by bhargavaurala** [comment]
Hi

**Comment by bhargavaurala** [comment]
Hello, please find the files in this location. It is publicly accessible.
https://drive.google.com/drive/folders/1JdntiX2SMZhmpmp_jTjnxAqKQqirxZHq?usp=sharing

**Comment by SriramPingali** [comment]
Hello @bhargavaurala , I tried to download the three files, but there seems to be a problem in extracting them. Could you guide me in extracting training data from .parta, .partb, .partc files? Thanks a lot!

**Comment by bhargavaurala** [comment]
Hello,

It should extract all parts if you just extract the first part i.e. .partaa as usual.

If not please try `cat AccessMathVOC.zip.part* | unzip`

**Comment by SriramPingali** [comment]
Thank you for the help @bhargavaurala ! Although doing the extractions gave me annotations for only 4 lectures, namely lecture 1, 6, 18, NM lecture 1. Was this supposed to happen or is the extraction done wrong?

PS: I did get the complete JPEG image folder for all the lectures.
