### ISSUE TITLE
Audio files for testing on own dataset

### ISSUE THREAD

**Issue by KunikaValecha** [bhargavaurala/accessmath-icfhr2018#3]
Hi, 

I am trying to test on my own dataset. For that, i guess i need to make changes in db_AccessMath2015.xml under test_data folder. There i found paths to audio files as well. Can you please tell where are they getting used? And can I just skip them?

Thanks.

**Comment by kdavila** [comment]
Hello.

Yes, modifying the XML is the right thing to do use it on new data. About
the audio files, these were used by earlier prototypes of the system but
currently this version doesn’t need them. You can omit them.
